server:
  port: 8080
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/jiangweigen/{application}
          username:
          password:
#          uri: https://github.com/jiangweigen/springConfig.git

