CREATE TABLE `changelog` (
  `CHANGE_NUMBER` int(22) NOT NULL,
  `COMPLETE_DT` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00' ON UPDATE CURRENT_TIMESTAMP,
  `APPLIED_BY` varchar(100) NOT NULL,
  `DESCRIPTION` varchar(500) NOT NULL,
  PRIMARY KEY (`CHANGE_NUMBER`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;