CREATE TABLE `changelog` (
  `CHANGE_NUMBER` BIGINT(15)   NOT NULL,
  `COMPLETE_DT`   TIMESTAMP    NOT NULL DEFAULT '0000-00-00 00:00:00' ON UPDATE CURRENT_TIMESTAMP,
  `APPLIED_BY`    VARCHAR(20)  NOT NULL,
  `DESCRIPTION`   VARCHAR(100) NOT NULL,
  PRIMARY KEY (`CHANGE_NUMBER`)
)
  ENGINE = InnoDB
  DEFAULT CHARSET = utf8;