mybatis:
  type-aliases-package: com.jiangwg.po
  mapper-locations: classpath:com/jiangwg/dao/**/*.xml
spring:
  datasource:
    platform: ${myvar.db.platform}
    schema: classpath:schema.sql
    data: classpath:data.sql
server:
  port: ${myvar.server.port}
  context-path: /springBoot

#logging:
#  config: classpath:logback-spring22.xml
