CREATE TABLE `a_user` (
  `id`       INT(11)      NOT NULL,
  `name`     VARCHAR(200) NOT NULL,
  `age`      INT(11)      DEFAULT NULL,
  `birthday` VARCHAR(8)   DEFAULT NULL
  COMMENT 'yyyyMMdd',
  `remark`   VARCHAR(299) DEFAULT NULL,
  PRIMARY KEY (`id`)
)
  ENGINE = InnoDB
  DEFAULT CHARSET = utf8
  /
-- RANGE分区
ALTER TABLE `a_user`
PARTITION BY RANGE (id) (
PARTITION `p0` VALUES LESS THAN (10),
PARTITION `p1` VALUES LESS THAN (20),
PARTITION `p2` VALUES LESS THAN ( MAXVALUE ) )
